name: build

on:
  - push
  - pull_request

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: brndnmtthws/rust-action-rustup@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin retry
        env:
          CARGO_TARGET_DIR: "./dist/"

      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: dist/release/retry
